- app/DApp.js
- modules/blockHandler.js
- modules/logger.js
> Registrable block handlers

- Blockchain.js
- main.js
- modules/validators.js
- shell/package-lock.json
- shell/package.json
Validators object has been added
added exchange of validators objects
> Validators

- Blockchain.js
- modules/starwaveCrypto.js
- modules/starwaveProtocol.js
Изменил библиотеку шифрования на cryptoJS для совместимости с клиентом. теперь код шифрования/расшифрования одинаковый везде
> Diffie hellman

- main.js
global.PATH.configDir
global.PATH.mainDir
проверяет как записано точка входа:
-если полный путь, оставляет
-если нет, то проверяет наличие файла в папке конфига, если не находит то точку входа ставит false
> Dapp paths

- modules/validators/dlcpoa.js
Dynamic complexity version of LCPoA
> DLCPoA Consensus

- BigNet/mainContract.js
- modules/smartContracts/internalModules/TokenContract.js
also added some convenient stuff to TokenContract
> order and direct sell methods added

- modules/smartContracts/EcmaContract.js
> Delayed call limiter

- modules/smartContracts/EcmaContract.js
Support for blacklisted methods
> Blacklisted methods

- .gitignore
- BigNet/mainContract.js
- BigNet/test/test.js
- app/DApp.js
- modules/smartContracts/EcmaContract.js
- modules/smartContracts/internalModules/BlockchainMap.js
DApp: ECMA promise style
MasterContract: C2C payments
ECMA: BlockchainObject deprecated
ECMA: BlockchainMap structure
> Contracts orders

- BigNet/mainContract.js
edited PR from mainToken-OrderSell
> Main token new os

- BigNet/mainContract.js
- BigNet/test/test.js
- modules/smartContracts/EcmaContract.js
- modules/smartContracts/internalModules/Contract.js
- modules/smartContracts/internalModules/SellerContractConnector.js
SellerContractConnector
MasterContract getter
C2C orders hooks
> SellerContractConnector

- modules/smartContracts/internalModules/Contract.js
Methods for external app interface register
> App register methods

- Blockchain.js
- main.js
- modules/blocks/candyData.js
- modules/cryptography.js
- modules/smartContracts/EcmaContract.js
- modules/smartContracts/blocks/EcmaContractCallBlock.js
- modules/smartContracts/blocks/EcmaContractDeployBlock.js
- modules/starwaveProtocol.js
- modules/wallet.js
- plugins/iz3-basic-crypto/README.md
- plugins/iz3-basic-crypto/index.js
- plugins/iz3-basic-crypto/package.json
- plugins/iz3-starwave-crypto/package.json
- plugins/iz3-starwave-crypto/starwaveCrypto.js
Moving all cryptography to external modules
getMasterContract fix
> External crypto

- Blockchain.js
- app/DApp.js
- modules/AccountManager.js
- modules/keyvalue.js
- modules/logger.js
- modules/smartContracts/EcmaContract.js
- modules/smartContracts/connectors/ContractConnector.js
- modules/smartContracts/connectors/TokenContractConnector.js
Account manager for working with multiple accounts
> Account manager

- api/php/EcmaSmartRPC.php
- modules/smartContracts/EcmaContract.js
- modules/smartContracts/connectors/ContractConnector.js
External signed block support for API
> External signed block support

- package.json
Ecma plugin support
Pluginable validators
Fixed maxBlock bug
> Release update

- BigNet/test/config.json
- BigNet/test/test.js
- package.json
> New WebSocket version

- modules/frontend.js
Added new implementation for new API method - getBlock by id
> Issue #65 getBlock by index API method

- api/node/NodeRPC.js
- api/node/terminal/terminal.js
- package.json
RPC fixes
Support for terminal connection string
> RPC terminal improve

- .github/workflows/npmpublish.yml
- api/node/README.MD
- api/node/package.json
- api/node/runTerminal
- api/node/runTerminal.bat
- package.json
> Terminal package update

- api/node/EcmaSmartRPC.js
- api/php/EcmaSmartRPC.php
- app/DApp.js
- modules/smartContracts/EcmaContract.js
Contract exists method for API & DApp
> Contract exists method

- api/node/package.json
Same api version as IZZZIO node
> Api version sync with node

- BigNet/mainContract.js
Changed checkContractAddress function
> fixed checking of contract address

- main.js
- modules/blockchain.js
- modules/cacheStorage.js
Added module CacheStorage.
Added config option cacheLifeTime
> Add cache for block data storing

- modules/cryptography.js
Deleted all references to old GOST modules
> Refactor cryptography

- Tests/ShardedDB/test/config.json
- plugins/iz3-db-sharded/shardedDB.js
Please enter the commit message for your changes. Lines starting
> fixes plugin and test config
